#-------------------------------
# General Site Settings

title: Scott Arakawa
logo: 
author: themefisher
description: Portfolio for Scott Arakawa  
email: scottarakawa@gmail.com
phone:
address: San Francisco, CA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}

#-------------------------------- 
# {name: Blog, link: '/blog'}
#-------------------------------
#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Scott <br> Full Stack Web Developer

social:
#- {icon: "ti-facebook", link: "#"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/scottarakawa/"}
- {icon: "ti-instagram", link: "https://www.instagram.com/sctkawa/"}
#- {icon: "ti-dribbble", link: "#"}
#- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb: Hi! I’m Scott and I graduated from Bloc as a full stack web developer, where I learned HTML, CSS, Javascript, Angular.js and Ruby on Rails. I’m excited to live and work in San Francisco. I’ve been working remotely for a company in Chicago for over a year and enjoy it a lot (and my dog does too). I hope to hear from you soon!

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
# work-process:
#  - title : "Research and Plan"
#    icon : "assets/images/icons/plan.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#  - title : "Design and Develop"
#    icon : "assets/images/icons/design.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#  - title : "Deliver"
#    icon : "assets/images/icons/print.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
#team:
 # - title : "Jack Schenziwe"
  #  image : "assets/images/team/member-1.png"
   # designation : "Project Manager"
    
 # - title : "Julias Carlie"
  #  image : "assets/images/team/member-2.png"
   # designation : "Web Developer"
    
 # - title : "John Doe"
  #  image : "assets/images/team/member-3.png"
   # designation : "Designer"


#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Web Design, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

# experience-title: Experience
# experience:
# - {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
# - {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
# - {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: BA in Digital Cinema and Minor in English Literature with highest honors, organization: 'DePaul University'}
- {name: Full Stack Web Development, organization: 'Bloc'}


#-------------------------------
# Services Section

# services-title: Services
# services:
# - {
#     name: UI Design,
#     icon: ti-palette,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }
# - {
#     name: UX Design,
#     icon: ti-vector,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: true # Add true to select section
#   }
# - {
#     name: Interaction Design,
#     icon: ti-panel,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/letschat.png"
    url: "https://lets-chat-sa.herokuapp.com/"
      
  - image : "assets/images/portfolio/tiptogether.png"
    url: "https://tip-together.herokuapp.com/"
      
  - image : "assets/images/portfolio/bloc-jams.png"
    url: "https://ibrunch-bloc-jams-angular.herokuapp.com/"

  - image : "assets/images/portfolio/tomatempo.png"
    url: "https://tomatempo-ibrunch.herokuapp.com/"


# Portfolio Page
portfolio-label:
- {
    title : "Let’s Chat",
    type : "lets-chat"
  }
- {
    title : "Tip-Together",
    type : "tip-together"
  }
- {
    title : "Bloc Jams",
    type : "bloc-jams"
  }
- {
    title : "TomaTempo",
    type : "toma-tempo"
  }

portfolio-items:
  - image : "assets/images/portfolio/letschat.png"
    url: "https://lets-chat-sa.herokuapp.com/"
    portfolio-type:
     - type: "lets-chat"
      
  - image : "assets/images/portfolio/tiptogether.png"
    url: "https://tip-together.herokuapp.com/"
    portfolio-type:
      - type: "tip-together"
      
  - image : "assets/images/portfolio/bloc-jams.png"
    url: "https://ibrunch-bloc-jams-angular.herokuapp.com/"
    portfolio-type:
      - type: "bloc-jams"
      
  - image : "assets/images/portfolio/tomatempo.png"
    url: "https://tomatempo-ibrunch.herokuapp.com/"
    portfolio-type:
      - type: "toma-tempo"
     

#-------------------------------
# Testimonials Section

# testimonial-items:
 #  - name: "Jesica Gomez"
 #   image: "assets/images/testimonial/client-1.png"
 #  designation : "CEO, Funder"
 #  content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
 #  - name: "Jesica Gomez"
 #    image: "assets/images/testimonial/client-1.png"
 #    designation: "CEO, Funder"
 #    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
 #  - name: "Jesica Gomez"
 #    image: "assets/images/testimonial/client-1.png"
 #    designation: "CEO, Funder"
 #    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
 

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: scottarakawa@gmail.com
